### ISSUE TITLE
Problem with running the code

### ISSUE THREAD

**Issue by arashakb** [randomizedheap/CR_Attack#1]
I am trying to run the final command as it is mentioned in the readme but i am getting this error 
_pickle.UnpicklingError: invalid load key, '<'.
any idea how to solve it?
anyone having the same issue?

**Comment by randomizedheap** [comment]
Hi which command are you running got this error, and could you provide the full error please?

**Comment by arashakb** [comment]
Hello,
Sure, I am running 
```
python3 whitebox_attack.py --config=configvoc_psp.json --norm=2 --eps=1
```
I have installed the dependencies and done the instructions about the dataset
and the error is as follows:
```
Traceback (most recent call last):
  File "whitebox_attack.py", line 139, in <module>
    main(args, config)
  File "whitebox_attack.py", line 43, in main
    checkpoint = torch.load(args.binname, map_location=torch.device('cpu'))
  File "/opt/conda/lib/python3.8/site-packages/torch/serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/opt/conda/lib/python3.8/site-packages/torch/serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '<'.
```

**Comment by randomizedheap** [comment]
could you also provide the pytorch version your using? This seems to be due to some bugs in serialization caused by different torch versions when loading the model file.

**Comment by arashakb** [comment]
I used print(torch.\_\_version\_\_) and the output is 2.0.1+cu117

**Comment by randomizedheap** [comment]
I think probably you can try to use conda or docker to switch to torch 1.7 to see whether it works or not. Thanks!

**Comment by arashakb** [comment]
I realized that the pth file wasn't downloaded properly...
